apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
spec:
  ports:
  - port: 80
    targetPort: docker-app-port 
    protocol: TCP
  selector:
    app: docker-ap
  type: LoadBalancer

  